allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  sharp: set this to true or false
minimumReleaseAgeExclude:
  - postcss@8.5.10
overrides:
  postcss@<8.5.10: ^8.5.10
